### ISSUE TITLE
Uncaught TypeError: Promise.defer is not a function

### ISSUE THREAD

**Issue by anhnhoktvn** [lloeki/ex-mode#110] opened 2015-11-08 03:28 UTC
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Ubuntu 15.04
**Thrown From**: [ex-mode](https://github.com/lloeki/ex-mode) package, v0.7.0

### Stack Trace

Uncaught TypeError: Promise.defer is not a function

```
At /home/anhnhoktvn/.atom/packages/ex-mode/lib/ex-state.coffee:59

TypeError: Promise.defer is not a function
  at Ex.write (/home/anhnhoktvn/.atom/packages/ex-mode/lib/ex.coffee:153:24)
  at Ex.w (/home/anhnhoktvn/.atom/packages/ex-mode/lib/ex.coffee:174:5)
  at /home/anhnhoktvn/.atom/packages/ex-mode/lib/ex.coffee:1:1
  at Command.execute (/home/anhnhoktvn/.atom/packages/ex-mode/lib/command.coffee:153:7)
  at ExState.processOpStack (/home/anhnhoktvn/.atom/packages/ex-mode/lib/ex-state.coffee:53:17)
  at ExState.pushOperations (/home/anhnhoktvn/.atom/packages/ex-mode/lib/ex-state.coffee:43:6)
  at ExViewModel.ViewModel.confirm (/home/anhnhoktvn/.atom/packages/ex-mode/lib/view-model.coffee:13:14)
  at ExViewModel.module.exports.ExViewModel.confirm (/home/anhnhoktvn/.atom/packages/ex-mode/lib/ex-view-model.coffee:35:5)
  at ExViewModel.confirm (/home/anhnhoktvn/.atom/packages/ex-mode/lib/ex-view-model.coffee:1:1)
  at ex-command-mode-input.ExCommandModeInputElement.confirm (/home/anhnhoktvn/.atom/packages/ex-mode/lib/ex-normal-mode-input-element.coffee:46:16)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:20)

```

### Commands

```
     -0:27.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  8x -0:27.5.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:20.5.0 tree-view:add-file (div.header.list-item)
     -0:20.4.0 blur (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:14.2.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  6x -0:14.2.0 blur (atom-text-editor.editor.mini.is-focused)
     -0:08.4.0 vim-mode:activate-insert-mode (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:08.1.0 core:paste (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:07.6.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  5x -0:06.8.0 editor:move-to-end-of-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:05.5.0 editor:select-to-end-of-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.6.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:02.0 ex-mode:open (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:01.9.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:01.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  3x -0:01.0 blur (atom-text-editor.editor.mini.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "term2"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-html-preview, v0.1.13
editor-stats, v0.17.0
ex-mode, v0.7.0
file-icons, v1.6.11
highlight-selected, v0.10.1
language-babel, v2.2.0
linter, v1.10.0
minimap, v4.16.0
php-twig, v4.0.0
project-manager, v2.6.5
symbols-tree-view, v0.10.1
sync-settings, v0.6.0
tasks, v2.5.1
term3, v0.19.2
terminal-panel, v1.14.1
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by jazzpi** [comment] 2016-08-15 21:57
Duplicate of #147 which is fixed in v0.11.0

**Closed by jazzpi** 2016-08-15 21:57 UTC
