### ISSUE TITLE
replace with tab

### ISSUE THREAD

**Issue by GaryFurash** [lloeki/ex-mode#98] opened 2015-08-28 14:57 UTC
running :%s/ - /\t/ig
turns 
PO_HDR Purchase Order Header- Header Record for Purchase Order
into 
PO_HDR Purchase Order HeadertHeader Record for Purchase Order
instead of replacing the "-" with a tab character? Is this user error?

**Comment by lloeki** [comment] 2015-08-28 21:34
duplicate of #93

**Closed by lloeki** 2015-08-28 21:34 UTC
Labels: duplicate
