### ISSUE TITLE
bang command '!'

### ISSUE THREAD

**Issue by codekitchen** [lloeki/ex-mode#145] opened 2016-05-25 18:37 UTC
One of the features I miss most often from vim is the ex-mode `!` command, which runs the current selection through the specified shell command and replaces the selection with the output of that command. One of the most basic examples is `:!sort`, which runs the selection through the `sort` shell command and replaces it with the sorted output.

**Comment by jazzpi** [comment] 2016-08-15 22:43
Duplicate of #7.

**Closed by jazzpi** 2016-08-15 22:43 UTC
Labels: duplicate
