### ISSUE TITLE
:w fails to save file

### ISSUE THREAD

**Issue by WhiteVoidia** [lloeki/ex-mode#75] opened 2015-07-28 14:05 UTC
After updating to 0.6.1 from 0.5.1, saving with `:w` is broken. No error is shown, but the file does not save unless I use `:w filename`.

Steps to reproduce:
1. Open an existing file that has some contents
2. Edit those contents
3. Use `:w`
4. Note how the tab name changed to the file's directory name, rather than the file name
5. Note that the file is unchanged
6. Use `:w` again
7. Notice that the tab name just went up a directory for some reason and file remains unchanged
8. Use `:w file.txt`
9. Note that it tries to save the file several directories above where the file started
10. Use `:w /absolute/path/to/file.txt`
11. Note that the file saves

**Comment by WhiteVoidia** [comment] 2015-07-28 14:09
I think it's pretty safe to assume that this (656ed90f7e5391ce7228f9da00f77423573403c2) commit caused the issue.

**Comment by JianxinMa** [comment] 2015-07-28 15:32
It is 0.6.1's fault. Because everything is right until just now when I updated it.

**Comment by ericmcdaniel** [comment] 2015-07-28 15:37
I am also having this issue.

**Comment by lloeki** [comment] 2015-07-28 15:57
Got it guys, I'll be looking into it. Sorry for the broken release.

**Comment by mleeds95** [comment] 2015-07-28 23:03
Sorry about that. PR #76 should fix it.

**Comment by ericmcdaniel** [comment] 2015-07-29 12:57
Good job!

**Comment by LorenzLeitner** [comment] 2015-07-29 12:59
Would be :ok_hand: if someone merged this PR and released an update.

**Closed** 2015-07-29 14:37 UTC

**Comment by lloeki** [comment] 2015-07-29 14:44
Released v0.6.2. Sorry for the regression.

**Comment by WhiteVoidia** [comment] 2015-07-29 14:48
Awesome, thanks for the quick response :+1:
