### ISSUE TITLE
Go to line number is off

### ISSUE THREAD

**Issue by 50Wliu** [lloeki/ex-mode#67] opened 2015-07-09 15:10 UTC
_From @msmaili on July 8, 2015 21:46_

I noticed whenever I try to go to a particular line, it's off by one.  I'm guessing it's just some indexing issue.

E.g., typing `:20` takes me to line 21.

Also, is there a way to show the bottom input bar when entering a line number?  That way I can see what line I'm typing?

_Copied from original issue: atom/vim-mode#749_

**Comment by 50Wliu** [comment] 2015-07-09 15:10
_From @bronson on July 9, 2015 1:1_

Hm, I can't reproduce this.

What type of file?  And does line wrapping affect it?

It's true, showing the keys typed in the status bar while in operator pending mode would be very cool.  And it would be more Vim-like.  That probably merits its own issue.

**Comment by 50Wliu** [comment] 2015-07-09 15:10
_From @msmaili on July 9, 2015 1:14_

To be honest, all files.  I'm pretty sure I have line wrapping completely disabled but if you tell me what the setting name is I can check to make sure.

I'll go ahead and open a new issue regarding the bar.

**Comment by 50Wliu** [comment] 2015-07-09 15:10
_From @bronson on July 9, 2015 1:33_

Might be related to https://github.com/atom/vim-mode/issues/716? You have ex-mode installed?

**Comment by 50Wliu** [comment] 2015-07-09 15:10
_From @jacekkopecky on July 9, 2015 6:54_

Typing `:20` would be an ex-mode command, so possibly this could be an
issue for that package, rather than vim-mode.

**Comment by 50Wliu** [comment] 2015-07-09 15:10
_From @msmaili on July 9, 2015 13:55_

Thanks for the clarification, I didn't realize ex-mode may be the package.

Is there a way to transfer issues between projects or should we just close this and open a new there?

**Comment by lloeki** [comment] 2015-07-29 14:57
Works for me here. Did you happen to have folded lines or something that could throw off stuff?

**Comment by heartedu** [comment] 2015-07-29 15:05
Not that I can think of.  Here's a copy of my config:

```
"*":
  welcome:
    showOnStartup: false
  core:
    disabledPackages: [
      "autocomplete-plus"
      "wrap-guide"
    ]
    themes: [
      "one-dark-ui"
      "solarized-dark-syntax"
    ]
  editor:
    invisibles: {}
    tabLength: 4
    scrollPastEnd: true
    scrollSensitivity: 30
    autoIndent: false
    autoIndentOnPaste: false
  "exception-reporting":
    userId: "ddaafd07-dffd-b252-48db-612909a97759"
  "bracket-matcher":
    autocompleteBrackets: false
    autocompleteSmartQuotes: false
  "vim-mode": {}
  whitespace:
    ensureSingleTrailingNewline: false
  "tree-view":
    hideIgnoredNames: false
    hideVcsIgnoredFiles: true
  "open-recent":
    maxRecentFiles: 15
    maxRecentDirectories: 5
    replaceProjectOnOpenDirectory: true
  "the-closer":
    closeWindowTogetherWithLastTab: false
```

Maybe you could try temporarily replacing your config with mine and seeing if the issue comes up?

**Comment by smaili** [comment] 2015-07-29 15:06
Not that I can think of.  Here's a copy of my config:

```
"*":
  welcome:
    showOnStartup: false
  core:
    disabledPackages: [
      "autocomplete-plus"
      "wrap-guide"
    ]
    themes: [
      "one-dark-ui"
      "solarized-dark-syntax"
    ]
  editor:
    invisibles: {}
    tabLength: 4
    scrollPastEnd: true
    scrollSensitivity: 30
    autoIndent: false
    autoIndentOnPaste: false
  "exception-reporting":
    userId: "ddaafd07-dffd-b252-48db-612909a97759"
  "bracket-matcher":
    autocompleteBrackets: false
    autocompleteSmartQuotes: false
  "vim-mode": {}
  whitespace:
    ensureSingleTrailingNewline: false
  "tree-view":
    hideIgnoredNames: false
    hideVcsIgnoredFiles: true
  "open-recent":
    maxRecentFiles: 15
    maxRecentDirectories: 5
    replaceProjectOnOpenDirectory: true
  "the-closer":
    closeWindowTogetherWithLastTab: false
```

Maybe you could try temporarily replacing your config with mine and seeing if the issue comes up?

**Comment by bronson** [comment] 2015-07-29 21:21
Even with soft wrap on and lines wrapping, :20 works correctly for me.

@smaili any chance you could record an example?  I use licecap, fwiw.

**Comment by smaili** [comment] 2015-07-30 02:08
Starting at line `1`, if I enter `:4`, I'm taken to line `5` instead of line `4`.
![a](https://cloud.githubusercontent.com/assets/4451986/8974267/abbb2c12-3624-11e5-8ecc-fb2c6e01bb0f.gif)

Now, from line `5`, if I enter `:6`, I'm taken to line `11` instead of line `6`.
![b](https://cloud.githubusercontent.com/assets/4451986/8974282/d1aac3b0-3624-11e5-91a9-b4370f49abd4.gif)

Judging from this behavior, what I think is happening is that whatever my current line number is, it takes the number I give it and adds it to that and takes me to that line - essentially doing a sum rather than a go to.  So because I'm at line `1` and give it `4`, it takes me to `5` because of `1 + 4 = 5`, and once I'm on line `5`, when I give it `6`, it takes me to `11` because of `5 + 6 = 11`.

Assuming my analysis is correct, is this by design?

**Comment by smaili** [comment] 2015-07-30 02:10
By the way Scott, thanks for the tip - licecap worked great! :+1:

**Comment by jacekkopecky** [comment] 2015-07-30 02:16
Oh, do you have the ex-mode package installed? This looks like it is doing
vim-mode operation 'enter' - go one line down, just with count.

**Comment by smaili** [comment] 2015-07-30 02:24
@jacekkopecky yes, I think that's why @50Wliu had moved this issue here from vim-mode.

I'm very curious to know whether this is the expected behavior or a bug because it's very annoying :)

**Comment by jazzpi** [comment] 2015-07-30 06:28
This is not expected behavior (it has the bug label :wink: ). Looks to me like it's interpreting `:4` as `:+4` for some reason :confused: ... But I can't reproduce it either.

As a temporary workaround, you could use <kbd>4</kbd><kbd>0</kbd><kbd>G</kbd>.

Does stuff like `:'a` (go to line with mark `a`) work?

Oh, and could you maybe download #83 for testing and see if the specs run? They should test for this behaviour.

**Comment by jacekkopecky** [comment] 2015-07-30 09:16
Forgive my unclear late night typing. I mean what if you actually *don't*
have ex-mode? Without ex-mode, `:` is ignored and what we see would
actually be the expected behaviour.

**Comment by smaili** [comment] 2015-07-31 14:29
Interesting news...I just realized this whole time I hadn't installed the `ex-mode` package!!!  Now that it's installed the line number issue has gone away.

Unless anyone else has the issue I had *with* the `ex-mode` package installed, I suggest closing this issue :)

**Comment by smaili** [comment] 2015-07-31 14:32
Although, now that we're on the topic...Is there a reason why `vim-mode` and `ex-mode` can't be merged into a single package?  They each contain vital functions that mimic vim so it feels a little weird that the packages are separated.

**Comment by 50Wliu** [comment] 2015-07-31 14:33
@smaili see https://github.com/atom/vim-mode/issues/596#issuecomment-125678155
Also, now I feel a bit bad for shunting this issue to `ex-mode` :(

**Comment by lloeki** [comment] 2015-07-31 14:33
@smaili see here for reasons: https://github.com/atom/vim-mode/issues/596#issuecomment-125678155

**Closed by lloeki** 2015-07-31 14:33 UTC
Labels: bug
